functionality:
  name: spaceranger_count
  namespace: alignment
  description: Align fastqs and detect tissues
  usage: |
    spaceranger count --input /path/to/bcl --sample \
      test_sample --id 13423 --lanes 1
  arguments:
    - type: file
      name: --input_fastqs
      description: Path to the fastq files.
      example: "/path/to/bcl"
      required: true
    - type: file
      name: --input_tif
      description: Path to the tif file
      example: "path/to/tif"
      required: true
    - type: file
      name: --reference_genome
      description: Path to the reference genome
      example: "path/to/ref_genome"
      required: true
    - type: file
      name: --output
      direction: output
      description: The name of the folder to store the results in
      default: outs
      required: true

    - type: string
      name: --id
      description: ID name for temporary output directory.
      default: output
    - type: string
      name: --sample
      description: Sample name to analyze.
      example: test_sample
    - type: integer
      name: --lanes
      description: Lanes associated with this sample. 
      example: 1
    - type: string
      name: --slide
      description: Slide associated with this sample. 
  resources:
    - type: python_script
      path: script.py
  # tests:
  #   - type: python_script
  #     path: test.py
  #   - path: ../../../test_resources
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/spaceranger:latest
  - type: native
  - type: nextflow